### ISSUE TITLE
Not able to Login Always showing error.

### ISSUE THREAD

**Issue by jatin-cbs** [Allar/ue4-mp-downloader#11]
![screenshot from 2018-07-26 10-30-30](https://user-images.githubusercontent.com/40650341/43242488-020cd3f2-90bf-11e8-8f2b-8acd5e3b3fd4.png)

**Comment by jatin-newacc** [comment]
Its working on Unreal Engine Market Place but its not working on your script.

**Comment by Narven** [comment]
Same issue here

**Comment by Jimster121** [comment]
Happens to me too.

**Comment by Goury** [comment]
@Allar why've you closed this one?
It isn't resolved, open it back.

**Comment by matheusfillipe** [comment]
Yeah @jatin-cbs  posted a url from another project. I have the exact same problem with this one and seems like now, in December 2020 there is nothing that works for linux for download UE4 contenc from epic store.

**Comment by Saladin1812** [comment]
@matheusfillipe  check my blog here for Unreal Engine marketplace on Linux https://blog.gamedev.tv/ue4-marketplace-linux/
It was uploaded yesterday.

**Comment by matheusfillipe** [comment]
Nice aproach @jatin-cbs ! I just did it. By the way this wont let me download whole sample projects like: 
![image](https://user-images.githubusercontent.com/24435787/101441777-9eab3f80-38f8-11eb-9467-b52ad233725b.png)

I saw that you can actually download UE4 there and run it with wine even :P but at least have it to install those things and then later you copy. Maybe there is a way to just fool around Epic games launcher and it will think UE4 is installed?

**Comment by Saladin1812** [comment]
Hmm will try to figure this out..  Thanks for sharing tho ! I only download assets usually so we dont need to install UE4 with wine for that as It can detect Unreal Engine projects location.. Will try if I can do something similar with the Engine. @matheusfillipe
