### ISSUE TITLE
Code Plugins fail to download with a 403 (Forbidden) error

### ISSUE THREAD

**Issue by Allar** [Allar/ue4-mp-downloader#2]

**Comment by Master-Foo** [comment]
I believe I'm getting the same error. I'll provide more info as the issue currently doesn't.

Here is a dump:

``` bash
Getting item build info.
Getting item manifest.
Error getting item manifest. Error code: 403
Failed to get item manifest. <?xml version="1.0" encoding="UTF-8"?><Error><Code>MissingKey</Code><Message>Missing Key-Pair-Id query parameter or cookie value</Message></Error>
```

I hate to complain about a problem if I can't offer a solution. Sorry, I don't think I'll be of much more use as I'm just starting with UE4 and I'm not far enough over the learning curve yet to dive into the details of the Marketplace. My ignorant assumption would be that the web API has changed. DUH! Yeah, I know, that's obvious, but that's probably the limit of help I can offer. Sorry to be **that** guy.

**Comment by hstone39** [comment]
Having the same exact problem when trying to download.
Getting item build info.
Getting item manifest.
Error getting item manifest. Error code: 403
Failed to get item manifest. <?xml version="1.0" encoding="UTF-8"?><Error><Code>MissingKey</Code><Message>Missing Key-Pair-Id query parameter or cookie value</Message></Error>

**Comment by Allar** [comment]
Aye, Epic has changed their API. I will look into this.

**Comment by SleepProgger** [comment]
It looks like the CDNs now needs `items.MANIFEST.signature` provided in the `itemBuildInfo`.
I changed this in
https://github.com/SleepProgger/ue4-mp-downloader/tree/fix_manifest_download

It is probably pretty ugly Javascript so no PR, just pick what you like.
I experienced timeouts so i changed the chunk download to only download one chunk at the time and got rid of the `download-file` dependency on the way.
I hope it helps, my nodejs experience is extremely limited.

**Comment by SleepProgger** [comment]
Even with the above fix there are problems with some types of assets (ContentExample fe.).
This is due to wrong chunk urls.
Luckily the path is the same as for the manifest file, so one can simply do:
```py
chunks = build_info['items']['CHUNKS']
base_url = chunks['distribution'] + chunks['path'].rsplit("/", 1)[0] + "/ChunksV3/"
url = base_url + group + "/" ....
```
