### ISSUE TITLE
Not seeing all of the assets purchased on the marketplace

### ISSUE THREAD

**Issue by olivoil** [Allar/ue4-mp-downloader#7]
Thanks for publishing this!

I can't see all of the assets I've purchased from the marketplace, for instance the animation starter pack isn't showing up. Wondering if it's a known issue and if there's a work around?

**Comment by Khyota** [comment]
That one in particular doesn't show up for me either, however it was free so not technically purchased.

**Comment by Khyota** [comment]
It's already been fixed in the pull request.
